#!/usr/bin/env python
# coding: utf-8
# Q1. What is a probability distribution, exactly? If the values are meant to be random, how can you predict them at all ?

Ans: A probability distribution describes how a random variable is distributed.

It tells us which values a random variable is most likely to take on and which values are less likely. Based on the previous data and the occurences of the random event, we can predict the outcome in terms of probabilities.



Q2. Is there a distinction between true random numbers and pseudo-random numbers, if there is one? Why are the latter considered “good enough”?

Ans: : True Random Numbers are true physical values while pseudo-random numbers are generated internally by a program . Latter is considered good enough as they have sort of uniform distribution. Pseudo random numbers are generated by computers using an algorithm (there are many) and a seed (either chosen by the user or, sometimes, clock time). They are not strictly random as, if you start with the same seed and same algorithm. A truly random number, on the other hand, is completely unpredictable. There is no way to generate a series of truly random numbers via computer; the usual ways are flipping coins, throwing darts, rolling dice and other physical processes.



Q3. What are the two main factors that influence the behaviour of a "normal" probability distribution ?

Ans: Normal Probability Distribution are influenced by two factors: Mean and Variance.



Q4. Provide a real-life example of a normal distribution ?

Ans: A Real-life example of a normal distribution are heights. Height of the population is the example of normal distribution. Most of the people in a specific population are of average height. The number of people taller and shorter than the average height people is almost equal, and a very small number of people are either extremely tall or extremely short.



Q5. In the short term, how can you expect a probability distribution to behave? What do you think will happen as the number of trials grows ?

Ans: Variance will decrease with number of trials. In probability theory and statistics, a probability distribution is the mathematical function that gives the probabilities of occurrence of different possible outcomes for an experiment.It is a mathematical description of a random phenomenon in terms of its sample space and the probabilities of events (subsets of the sample space).

Q6. What kind of object can be shuffled by using random.shuffle ?

Ans: lists (list), strings (str) and tuples (tuple) objects can be shuffled by using random.shuffle.



Q7. Describe the math package's general categories of functions ?
Ans: The Math package's general categories of functions are:

Trigonometric functions
Quadratic functions
Exponential functions
Hyperbolic functions
Periodic functions
Arithmetic functions
Logarithimic functions
Conversions to Integer
Q8. What is the relationship between exponentiation and logarithms ?
Ans: Exponentiation and logarithms are inverse of each other.

Q9. What are the three logarithmic functions that Python supports ?
Ans: The Three Logarithmic Functions that Python supports are:

log2(x) - logarithmic value of x to base 2
log10(x) - logarithmic value of x to base 10
log1p(a) - This function is used to compute logarithm(1+a) .